### ISSUE TITLE
Trouble installing "bvh-distance-queries" under Windows 11

### ISSUE THREAD

**Issue by MaxGodTier** [YuliangXiu/ICON#11]
I've managed to compile and install all dependencies, except this last one. Google doesn't really find any helpful result for this error, so any help is much appreciated!
Here's the log:
```
python setup.py install
running install
running bdist_egg
running egg_info
writing bvh_distance_queries.egg-info\PKG-INFO
writing dependency_links to bvh_distance_queries.egg-info\dependency_links.txt
writing requirements to bvh_distance_queries.egg-info\requires.txt
writing top-level names to bvh_distance_queries.egg-info\top_level.txt
adding license file 'LICENSE'
writing manifest file 'bvh_distance_queries.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'bvh_distance_queries_cuda' extension
Emitting ninja build file C:\bvh-distance-queries\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\bvh-distance-queries\build\temp.win-amd64-3.8\Release\src/bvh_cuda_op.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\THC -Iinclude -Icuda-samples/Common -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\bvh-distance-queries\src\bvh_cuda_op.cu -o C:\bvh-distance-queries\build\temp.win-amd64-3.8\Release\src/bvh_cuda_op.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DPRINT_TIMINGS=0 -DDEBUG_PRINT=0 -DERROR_CHECKING=1 -DNUM_THREADS=256 -DPROFILING=0 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=bvh_distance_queries_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61
FAILED: C:/bvh-distance-queries/build/temp.win-amd64-3.8/Release/src/bvh_cuda_op.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\bvh-distance-queries\build\temp.win-amd64-3.8\Release\src/bvh_cuda_op.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\THC -Iinclude -Icuda-samples/Common -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\include -IC:\ProgramData\Anaconda3\envs\pttf2cu113py38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\bvh-distance-queries\src\bvh_cuda_op.cu -o C:\bvh-distance-queries\build\temp.win-amd64-3.8\Release\src/bvh_cuda_op.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DPRINT_TIMINGS=0 -DDEBUG_PRINT=0 -DERROR_CHECKING=1 -DNUM_THREADS=256 -DPROFILING=0 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=bvh_distance_queries_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61
C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: 'HAVE_SNPRINTF': macro redefinition
C:\ProgramData\Anaconda3\envs\pttf2cu113py38\include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: 'HAVE_SNPRINTF': macro redefinition
C:\ProgramData\Anaconda3\envs\pttf2cu113py38\include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
C:\bvh-distance-queries\src\aabb.hpp(34): error: attributes are not allowed here

C:\bvh-distance-queries\src\triangle.hpp(33): error: attributes are not allowed here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "start" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "stop" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "distances_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "dev_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "points_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "distances_dest_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "distances_dest_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected a ";"

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): warning: variable "triangles_ptr" was declared but never referenced

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "start" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "stop" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "distances_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "dev_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "points_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "distances_dest_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: identifier "distances_dest_ptr" is undefined

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: "#" not expected here

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected an expression

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): error: expected a ";"

C:\bvh-distance-queries\src\bvh_cuda_op.cu(900): warning: variable "triangles_ptr" was declared but never referenced

90 errors detected in the compilation of "C:/bvh-distance-queries/src/bvh_cuda_op.cu".
bvh_cuda_op.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    setup(name=NAME,
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\utils\cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\utils\cpp_extension.py", line 708, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\utils\cpp_extension.py", line 1399, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\ProgramData\Anaconda3\envs\pttf2cu113py38\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by YuliangXiu** [comment]
@MaxGodTier I have replaced the `bvh-distance-queries` with `PyTorch3D+Kaolin`, thus you don't need to install it anymore,
