### ISSUE TITLE
Colab: error !source activate icon && python -m apps.infer -cfg ./configs/filter.yaml -loop_smpl 100 -loop_cloth 200 -colab -gpu 0 -export_video -in_dir ./examples

### ISSUE THREAD

**Issue by dotrannhattuong** [YuliangXiu/ICON#117]
Traceback (most recent call last):
  File "/usr/local/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/ICON/apps/infer.py", line 236, in <module>
    "T_normal_B"] = dataset.render_normal(
  File "/content/ICON/lib/dataset/TestDataset.py", line 303, in render_normal
    return self.render.get_rgb_image()
  File "/content/ICON/lib/common/render.py", line 309, in get_rgb_image
    rendered_img = (self.renderer(
  File "/usr/local/envs/icon/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 61, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 247, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "/usr/local/envs/icon/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 224, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "/usr/local/envs/icon/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 298, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by YuliangXiu** [comment]
Choose GPU-mode as follows:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/7944350/191877513-42e5b61e-6dbe-4a0b-bb93-3c9c64825138.png">
