### ISSUE TITLE
pip install git+https://github.com/YuliangXiu/neural_voxelization_layer.git install failed

### ISSUE THREAD

**Issue by weiforce** [YuliangXiu/ICON#119]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running install
/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing voxelize_cuda.egg-info/PKG-INFO
writing dependency_links to voxelize_cuda.egg-info/dependency_links.txt
writing top-level names to voxelize_cuda.egg-info/top_level.txt
writing manifest file 'voxelize_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setup(
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/root/miniconda/envs/icon/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 406, in build_extensions
    self._check_cuda_version()
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 782, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/root/miniconda/envs/icon/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by weiforce** [comment]
The original environment was installed in the Fedora Silverblue Docker environment. Now the problem of using a physical machine does not occur again.

**Comment by YuliangXiu** [comment]
https://github.com/YuliangXiu/neural_voxelization_layer/issues/2
