### ISSUE TITLE
the file 'smpl_param.pkl' have no key 'full_pose'

### ISSUE THREAD

**Issue by tdqcb** [YuliangXiu/ICON#122]
I changed code according the method that you provided,but new problem occured .the file 'smpl_param.pkl' have no key 'full_pose',then I change 'full_pose' to 'body pose',but the shape is error,can you give me some help?

(icon) gdl@gdl:~/Desktop/wangting/ICON-master$ python -m lib.dataloader_demo -v -c ./configs/train/pamir.yaml
/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
{'global_orient': array([[-0.2577994 ,  1.3495909 , -0.19527189]]), '**body_pose':** array([[[ 1.46435215e-01, -4.48708190e-03,  1.89517323e-01],
        [-6.21869468e-01, -1.05050030e-01, -4.34111741e-02],
        [ 2.63547037e-01, -1.52487207e-01,  1.56659802e-01],
        [-1.71819317e-01, -1.64465648e-01,  4.40432130e-02],
        [ 1.67020235e+00, -8.67289795e-02,  3.06503940e-01],
        [-2.72811443e-01, -4.31228779e-04,  7.82719621e-02],
        [ 2.58956031e-01,  1.72923610e-01,  3.58472838e-03],
        [-4.91317612e-01, -2.39451260e-01,  3.36559021e-01],
        [ 2.61760222e-01, -1.14892970e-02,  7.03994970e-02],
        [-6.82931698e-01,  5.37374971e-01,  2.42266410e-02],
        [ 2.00156330e-01,  2.64839684e-01, -2.95057164e-01],
        [-3.08961783e-02, -1.73576950e-01,  3.68249540e-01],
        [-2.71585852e-01, -7.26955701e-03,  3.52532446e-01],
        [-3.62987465e-02, -1.10712132e-02,  1.25950698e-01],
        [ 3.27744427e-02, -3.51352246e-01, -1.74528572e-01],
        [ 3.99068150e-03, -2.15150290e-01,  1.16452384e-01],
        [ 1.79884334e-01,  1.57995513e-01,  1.00093164e+00],
        [-2.02023344e-01, -1.81487666e+00,  8.84970364e-01],
        [ 5.20967808e-02,  2.57767114e-01, -3.28617492e-01],
        [ 3.67027066e-01, -7.73467833e-02,  4.61679879e-01],
        [ 7.49815512e-01, -3.20876300e-01, -4.45156718e-01],
        [-1.22876506e+00, -4.92107497e-01, -1.93734096e+00],
        [-1.22736314e+00,  4.99016179e-01,  1.72180648e+00]]]), 'betas': array([[ 0.762956  , -1.0266448 ,  0.4842316 ,  0.39761072, -0.81847614,
         0.22849987,  0.8460495 ,  0.46218655,  1.042012  ,  1.5854723 ]],
      dtype=float32), 'transl': TrackedArray([[ 0.00035985,  0.05110257, -0.01051249]]), 'scale': array([0.3176894])}
Traceback (most recent call last):
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataloader_demo.py", line 41, in <module>
    data_dict = dataset[1]
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 285, in __getitem__
    data_dict.update(self.load_smpl_voxel(data_dict))
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 553, in load_smpl_voxel
    smpl_verts, smpl_faces, pad_v_num, pad_f_num = self.compute_voxel_verts(
  File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PIFuDataset.py", line 421, in compute_voxel_verts
    torch.as_tensor(smpl_param['full_pose'][0])).numpy()
**KeyError: 'full_pose'**

**change 'full_pose' to 'body pose',the new problem:**
File "/home/gdl/Desktop/wangting/ICON-master/lib/pare/pare/utils/geometry.py", line 242, in rotation_matrix_to_quaternion
    raise ValueError(
**ValueError: Input size must be a N x 3 x 4  tensor. Got torch.Size([23, 3])**

_Originally posted by @tdqcb in https://github.com/YuliangXiu/ICON/issues/121#issuecomment-1271596127_

**Comment by YuliangXiu** [comment]
It should work for now, please check [commit](https://github.com/YuliangXiu/ICON/commit/41fbc19b2c260efb0a7e38d95c4f116dbf22732c) for the update.

**Comment by tdqcb** [comment]
Thank you very much for your help，but whe I run '**python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml**' ,there some problem happened.How can I solve it?

Traceback (most recent call last):
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gdl/Desktop/wangting/ICON-master/apps/train.py", line 137, in <module>
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 856, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 725, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 164, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 177, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 131, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  **File "/home/gdl/Desktop/wangting/ICON-master/apps/ICON.py", line 275, in validation_step
    in_tensor_dict.update({key: batch[key]})**
**KeyError: 'smpl_vis'**
