### ISSUE TITLE
KeyError: 'smpl_vis

### ISSUE THREAD

**Issue by tdqcb** [YuliangXiu/ICON#123]
Thank you very much for your help，but whe I run '**python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml**' ,there some problem happened.How can I solve it?

Traceback (most recent call last):
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gdl/Desktop/wangting/ICON-master/apps/train.py", line 137, in <module>
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 856, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 725, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 164, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 177, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 131, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  **File "/home/gdl/Desktop/wangting/ICON-master/apps/ICON.py", line 275, in validation_step
    in_tensor_dict.update({key: batch[key]})**
**KeyError: 'smpl_vis'**

_Originally posted by @tdqcb in https://github.com/YuliangXiu/ICON/issues/122#issuecomment-1272296550_

**Comment by YuliangXiu** [comment]
I test `python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml` and it works well. It seems that you're using old version of ICON, please re-clone the latest version.

**Comment by tdqcb** [comment]
yes,after I updated the code ,the follow error  dispeared. but the out_dic['vis'] is None,this is correct?

gdl@gdl:~/Desktop/wangting/ICON-master$ CUDA_VISIBLE_DEVICES=0 python -m apps.train -cfg ./configs/train/icon-filter.yaml
load from ./data/thuman2/train.txt
total: 504
load from ./data/thuman2/val.txt
total: 24
ICON:
w/ Global Image Encoder: True
Image Features used by MLP: ['normal_F', 'normal_B']
Geometry Features used by MLP: ['sdf', 'cmap', 'norm', 'vis']
Dim of Image Features (local): 6
Dim of Geometry Features (ICON): 7
Dim of MLP's first layer: 13

GPU available: True, used: True
TPU available: None, using: 0 TPU cores
Resume MLP weights from ./data/ckpt/icon-filter.ckpt
Resume normal model from ./data/ckpt/normal.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name        | Type          | Params
----------------------------------------------
0 | netG        | HGPIFuNet     | 372 M 
1 | reconEngine | Seg3dLossless | 0     
----------------------------------------------
372 M     Trainable params
0         Non-trainable params
372 M     Total params
1,489.083 Total estimated model params size (MB)
Validation sanity check:   0%|                            | 0/1 [00:00<?, ?it/s]
**out_dict["vis"] None**
Traceback (most recent call last):
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gdl/Desktop/wangting/ICON-master/apps/train.py", line 137, in <module>
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 856, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 725, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 164, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 177, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 131, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/gdl/Desktop/wangting/ICON-master/apps/ICON.py", line 277, in validation_step
    preds_G, error_G = self.netG(in_tensor_dict)
  File "/home/gdl/anaconda3/envs/icon/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gdl/Desktop/wangting/ICON-master/lib/net/HGPIFuNet.py", line 420, in forward
    preds_if_list = self.query(in_feat,
  File "/home/gdl/Desktop/wangting/ICON-master/lib/net/HGPIFuNet.py", line 307, in query
    point_feat_out = point_feat_extractor.query(
  **File "/home/gdl/Desktop/wangting/ICON-master/lib/dataset/PointFeat.py", line 83, in query
    out_dict["vis"] = out_dict["vis"].ge(1e-1).float()**
**AttributeError: 'NoneType' object has no attribute 'ge'**

**Comment by YuliangXiu** [comment]
It works now. BTW, I am in the deadline mode, thus I won't be active to update this repo in the next two months.
