### ISSUE TITLE
KeyError: 'smpl_param'

### ISSUE THREAD

**Issue by DeepSight-TS** [YuliangXiu/ICON#131]
Hi, I am very interested in your work and want to try. But I got an error when I run **python -m apps.train -cfg ./configs/train/pamir.yaml -test**
````
Original Traceback (most recent call last):
  File "/mnt/f/envs/icon/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/f/envs/icon/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/f/envs/icon/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/f/code/Python/ICON/lib/dataset/PIFuDataset.py", line 251, in __getitem__
    data_dict.update(self.load_smpl_voxel(data_dict))
  File "/mnt/f/code/Python/ICON/lib/dataset/PIFuDataset.py", line 488, in load_smpl_voxel
    smpl_verts, smpl_faces, pad_v_num, pad_f_num = self.compute_voxel_verts(
  File "/mnt/f/code/Python/ICON/lib/dataset/PIFuDataset.py", line 368, in compute_voxel_verts
    smpl_param = np.load(data_dict['smpl_param'], allow_pickle=True)
KeyError: 'smpl_param'
````
I find that the function `compute_voxel_verts` need `smpl_param` and `smplx_param`, but there are no these param when `dataset == 'cape'`. Is this a bug?

**Comment by YuliangXiu** [comment]
CAPE testset contains SMPL fits under `./fits`, please check [evaluation](https://github.com/YuliangXiu/ICON/blob/master/docs/evaluation.md#cape-testset).

**Comment by YuliangXiu** [comment]
@DeepSight-TS I have updated the code for PaMIR-CAPE testing.

`./cape/smpl`: 
- `npz` -- SMPL parameters
- `npy` -- SMPL keypoints
- `obj` -- SMPL meshes

**Comment by DeepSight-TS** [comment]
> @DeepSight-TS I have updated the code for PaMIR-CAPE testing. And please download CAPE testset using [fetch_cape.sh](https://github.com/YuliangXiu/ICON/blob/master/fetch_cape.sh)
> 
> `./cape/smpl`:
> 
> * `npz` -- SMPL parameters
> * `npy` -- SMPL keypoints
> * `obj` -- SMPL meshes

Thank you very much!
