### ISSUE TITLE
ModuleNotFoundError: No module named 'rembg.session_factory'

### ISSUE THREAD

**Issue by VintageCar** [YuliangXiu/ICON#148]
Hi,
Thank you for the great work and codes.
 When I first run the demo in Google Colab, I got this error as follows:

> Traceback (most recent call last):
  File "/usr/local/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/ICON/apps/infer.py", line 25, in <module>
    from lib.common.render import query_color, image2vid
  File "/content/ICON/lib/common/render.py", line 36, in <module>
    from lib.dataset.mesh_util import get_visibility
  File "/content/ICON/lib/dataset/mesh_util.py", line 32, in <module>
    from lib.pymaf.utils.imutils import uncrop
  File "/content/ICON/lib/pymaf/utils/imutils.py", line 8, in <module>
    from rembg.session_factory import new_session
ModuleNotFoundError: No module named 'rembg.session_factory'

I found the default rembg branch in requirements_colab.txt is:

> git+https://github.com/YuliangXiu/rembg.git@hf

,but the 'session_factory' is only definded in main branch.

Well, using the main branch will solve this error!

Thinks!

**Comment by nosy-b** [comment]
@VintageCar I took away the "_@hf"_ in _requirements_colab.txt_  and it works now
-> git+[https://github.com/YuliangXiu/rembg.git](https://github.com/YuliangXiu/rembg.git)
