### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by Zhangjzh** [YuliangXiu/ICON#164]
After training of the implicit MLP, I got quite wired results. The reconstructed meshes are poor.
![0_nc](https://user-images.githubusercontent.com/49779683/208625149-c30b22e5-966b-4e23-8d87-d92006a6d7e0.png)
The evaluation results shows that NC is very low, but chamfer and p2s are very high.
![eval](https://user-images.githubusercontent.com/49779683/208625491-4c5cde58-fab1-4bcc-8fbf-3301f49ccb67.png)
Do you know where the problem is? I would appreciate it a lot if you could give me some suggestions!

**Comment by YuliangXiu** [comment]
Please firstly do visualization to check the input data (scans, SMPL, image, etc) are well aligned, see [training.md](https://github.com/YuliangXiu/ICON/blob/master/docs/training.md).

```bash

# visualization for SMPL-X mesh
python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml

# visualization for voxelized SMPL
python -m lib.dataloader_demo -v -c ./configs/train/pamir.yaml
```

**Comment by Zhangjzh** [comment]
Ok, I will have a try. Thank you very much!

**Comment by Yuhuoo** [comment]
I find there are may some problems in the preprocess scripts. I use the scripts preprocessing the THuman2.0 dataset, but the preprocessed data cannot aligned to the smplx mesh. 
![Xnip2023-01-07_18-11-39](https://user-images.githubusercontent.com/91204817/211145925-a708ca4f-2b6a-4800-989d-c9dbf7931ac4.jpg)
 I need to download the SMPL+X.zip again to align the smplx mesh and the prepocessed data. 
![Xnip2023-01-07_18-18-11](https://user-images.githubusercontent.com/91204817/211145947-7ed6b226-2021-4d3a-93ee-ec0b025cdcbc.jpg)
But I checked the smplx mesh hasn't be changed after the preprocess. The problem others also meet, and this will lead to the failure of training. That's so strange! Can you share some solution about this? Very Thanks!

**Comment by YuliangXiu** [comment]
Hi @Zhangjzh  and @Yuhuoo 

I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).

Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:

```bash
conda activate icon
python -m scripts.render_batch -headless -out_dir data/
```

**Comment by Yuhuoo** [comment]
> Hi @Zhangjzh and @Yuhuoo
> 
> I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).
> 
> Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:
> 
> ```shell
> conda activate icon
> python -m scripts.render_batch -headless -out_dir data/
> ```
> 
> Now `data/thuman2/smplx/xxxx.obj` and `data/thuman2/scans/xxxx.obj` are aligned perfectly
> 
> ![image](https://user-images.githubusercontent.com/7944350/211197590-bb093b06-31c0-436e-b40e-e9979703b648.png)

Very thanks for your reply and resolutions. But I have meet the problems as follows using the scripts, I have tried many ways to solve the problems and I failed. Can you meet the problems?

The complete error message are as follows:

Start Rendering thuman2 with 36 views, 512x512 size.
Output dir: ./debug/thuman2_36views
Rendering types: ['light', 'normal', 'depth']
  0%|                                                                                                     | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/miniconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/hy-tmp/ICON/scripts/render_batch.py", line 224, in <module>
    for _ in tqdm(
  File "/usr/local/miniconda3/envs/icon/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/usr/local/miniconda3/envs/icon/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f89f2e9f5b0>'. Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'

**Comment by YuliangXiu** [comment]
Very strange, this works well for me.

![image](https://user-images.githubusercontent.com/7944350/211502265-92ce40d7-ddb9-41fa-804b-86ed8c7877b1.png)

**Comment by Zhangjzh** [comment]
> > Hi @Zhangjzh and @Yuhuoo
> > I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).
> > Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:
> > ```shell
> > conda activate icon
> > python -m scripts.render_batch -headless -out_dir data/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now `data/thuman2/smplx/xxxx.obj` and `data/thuman2/scans/xxxx.obj` are aligned perfectly
> > ![image](https://user-images.githubusercontent.com/7944350/211197590-bb093b06-31c0-436e-b40e-e9979703b648.png)
> 
> Very thanks for your reply and resolutions. But I have meet the problems as follows using the scripts, I have tried many ways to solve the problems and I failed. Can you meet the problems?
> 
> The complete error message are as follows:
> 
> ```shell
> Start Rendering thuman2 with 36 views, 512x512 size.
> Output dir: ./debug/thuman2_36views
> Rendering types: ['light', 'normal', 'depth']
>   0%|                                                                                                     | 0/2 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/usr/local/miniconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/miniconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/hy-tmp/ICON/scripts/render_batch.py", line 224, in <module>
>     for _ in tqdm(
>   File "/usr/local/miniconda3/envs/icon/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
>     for obj in iterable:
>   File "/usr/local/miniconda3/envs/icon/lib/python3.8/multiprocessing/pool.py", line 868, in next
>     raise value
> multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f89f2e9f5b0>'. Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> ```

Hi, I ran into the same problem as you do. Did you solve the problem?

**Comment by yxt7979** [comment]
> 
you can try this:
change 
for gpu_ids in range(NUM_GPUS):
        for _ in range(PROC_PER_GPU):
                queue.put(gpu_ids )
to
queue.put(0)

**Comment by yxt7979** [comment]
> Hi @Zhangjzh and @Yuhuoo
> 
> I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).
> 
> Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:
> 
> ```shell
> conda activate icon
> python -m scripts.render_batch -headless -out_dir data/
> ```
> 
> Now `data/thuman2/smplx/xxxx.obj` and `data/thuman2/scans/xxxx.obj` are aligned perfectly
> 
> ![image](https://user-images.githubusercontent.com/7944350/211197590-bb093b06-31c0-436e-b40e-e9979703b648.png)

您好，我遇到了楼主一样的问题（NC=0.2，P2S=4.)，在我重新下载SMPL-X.zip并render_batch之后，检查了两个.obj是对齐的，但是用git clone repo最新版的ICON代码训练模型还是有问题，甚至比改动前结果指标差距更大了（P2S 40）。
在训练中，模型对cape的表现越来越差：
![image](https://user-images.githubusercontent.com/62125435/213185370-9a852f0e-5abe-4b77-a74b-c2cfd2e066b5.png)
虽然指标比较正常，但是我在测试的时候将cape换成thuman2验证集的5个数据发现效果也不好：
![image](https://user-images.githubusercontent.com/62125435/213185830-5a9241d3-8c6b-422e-a906-ca5474cb7838.png)
![image](https://user-images.githubusercontent.com/62125435/213185932-1707f746-b379-423f-a9f9-dc91a7395916.png)
由于我是服务器，无法用python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml来检验训练数据是否正确，请问可否有其他方法查看训练数据是否有问题？为什么同一个模型对cape和thuman2的结果差距很大？如何改正可以复现出论文中的训练精度呢？
很期待您的指教，谢谢

**Comment by Zhangjzh** [comment]
> > Hi @Zhangjzh and @Yuhuoo
> > I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).
> > Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:
> > ```shell
> > conda activate icon
> > python -m scripts.render_batch -headless -out_dir data/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now `data/thuman2/smplx/xxxx.obj` and `data/thuman2/scans/xxxx.obj` are aligned perfectly
> > ![image](https://user-images.githubusercontent.com/7944350/211197590-bb093b06-31c0-436e-b40e-e9979703b648.png)
> 
> 您好，我遇到了楼主一样的问题（NC=0.2，P2S=4.)，在我重新下载SMPL-X.zip并render_batch之后，检查了两个.obj是对齐的，但是用git clone repo最新版的ICON代码训练模型还是有问题，甚至比改动前结果指标差距更大了（P2S 40）。 在训练中，模型对cape的表现越来越差： ![image](https://user-images.githubusercontent.com/62125435/213185370-9a852f0e-5abe-4b77-a74b-c2cfd2e066b5.png) 虽然指标比较正常，但是我在测试的时候将cape换成thuman2验证集的5个数据发现效果也不好： ![image](https://user-images.githubusercontent.com/62125435/213185830-5a9241d3-8c6b-422e-a906-ca5474cb7838.png) ![image](https://user-images.githubusercontent.com/62125435/213185932-1707f746-b379-423f-a9f9-dc91a7395916.png) 由于我是服务器，无法用python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml来检验训练数据是否正确，请问可否有其他方法查看训练数据是否有问题？为什么同一个模型对cape和thuman2的结果差距很大？如何改正可以复现出论文中的训练精度呢？ 很期待您的指教，谢谢

After re-downloading the SMPL-X.zip, I got well results.
![0_nc](https://user-images.githubusercontent.com/49779683/213342490-b0f14dd7-c069-4c3b-827a-eab886438c59.png)
I didn't re-run the data generation scripts, because I ran into some trouble and I didn't figure out how to solve it. But when I ran python -m lib.dataloader_demo -v -c ./configs/train/icon-filter.yaml, I got well aligned results.
![图片1](https://user-images.githubusercontent.com/49779683/213342968-5bf797a7-d3ef-4e52-a892-5b2c527ea907.png)
Hope this will help you.

**Comment by yxt7979** [comment]
> 
hi! thank you so much! Do you use the latest code in repo? I didn`t change the code and get wrong results, could you please share your train loss? is it the same like this in the first epoch?
![image](https://user-images.githubusercontent.com/62125435/213352147-0b40e826-ae46-4199-8a4a-b03ea96cfa16.png)

**Comment by cucdengjunli** [comment]
SAME QUESTION

**Comment by yxt7979** [comment]
> SAME QUESTION

after `change trimesh version to 3.17.1` , the .obj under /thuman2/smplx/ is right

**Comment by gushengbo** [comment]
> > > Hi @Zhangjzh and @Yuhuoo
> > > I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).
> > > Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:
> > > ```shell
> > > conda activate icon
> > > python -m scripts.render_batch -headless -out_dir data/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Now `data/thuman2/smplx/xxxx.obj` and `data/thuman2/scans/xxxx.obj` are aligned perfectly
> > > ![image](https://user-images.githubusercontent.com/7944350/211197590-bb093b06-31c0-436e-b40e-e9979703b648.png)
> > 
> > 
> > Very thanks for your reply and resolutions. But I have meet the problems as follows using the scripts, I have tried many ways to solve the problems and I failed. Can you meet the problems?
> > The complete error message are as follows:
> > ```shell
> > Start Rendering thuman2 with 36 views, 512x512 size.
> > Output dir: ./debug/thuman2_36views
> > Rendering types: ['light', 'normal', 'depth']
> >   0%|                                                                                                     | 0/2 [00:00<?, ?it/s]
> > Traceback (most recent call last):
> >   File "/usr/local/miniconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/local/miniconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/hy-tmp/ICON/scripts/render_batch.py", line 224, in <module>
> >     for _ in tqdm(
> >   File "/usr/local/miniconda3/envs/icon/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
> >     for obj in iterable:
> >   File "/usr/local/miniconda3/envs/icon/lib/python3.8/multiprocessing/pool.py", line 868, in next
> >     raise value
> > multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f89f2e9f5b0>'. Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'
> > ```
> 
> Hi, I ran into the same problem as you do. Did you solve the problem?

@yxt7979 @Zhangjzh @YuliangXiu  I have the same question too.  May I ask how to solve it?

**Comment by gushengbo** [comment]
hello, excuse me, @YuliangXiu @yxt7979  download SMPL-x again, and change trimesh version to 3.17.1, but I also meet the same problem.
data/thuman2/smplx/xxxx.obj and data/thuman2/scans/xxxx.obj are unaligned.

**Comment by gushengbo** [comment]
> hello, excuse me, @YuliangXiu @yxt7979 download SMPL-x again, and change trimesh version to 3.17.1, but I also meet the same problem. data/thuman2/smplx/xxxx.obj and data/thuman2/scans/xxxx.obj are unaligned.
> 
> ![微信图片_20230209131610](https://user-images.githubusercontent.com/122679046/217724400-92d5d180-a4fd-4495-a065-cd8cd3e91466.png)

I find that's wrong when I run the previous code, but it's right when I run lastest code.
However, when I run lastest code, I meet the problem:
(icon) shengbo@user-SYS:~/ICON-master$ python -m scripts.render_batch -debug -headless
Start Rendering thuman2 with 36 views, 512x512 size.
Output dir: ./debug/thuman2_36views
Rendering types: ['light', 'normal', 'depth']
  0%|                                                             | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/shengbo/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shengbo/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shengbo/ICON-master/scripts/render_batch.py", line 254, in <module>
    for _ in tqdm(
  File "/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/shengbo/anaconda3/envs/icon/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f216d3fe7f0>'. Reason: 'ValueError('ctypes objects containing pointers cannot be pickled')'

**Comment by gushengbo** [comment]
@Zhangjzh @Yuhuoo hello, have you solved this problem?

**Comment by AndrewMorgan2** [comment]
@gushengbo did you find any solution?

**Comment by dongdozizi** [comment]
@Zhangjzh @Yuhuoo @AndrewMorgan2 hello, how did you download the smpl-x.zip, now I found the link is 404 not found.

**Comment by AndrewMorgan2** [comment]
Please make a new issue if you have a new question

**Comment by glorioushonor** [comment]
> Hi @Zhangjzh and @Yuhuoo
> 
> I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).
> 
> Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:
> 
> ```shell
> conda activate icon
> python -m scripts.render_batch -headless -out_dir data/
> ```
> 
> Now `data/thuman2/smplx/xxxx.obj` and `data/thuman2/scans/xxxx.obj` are aligned perfectly
> 
> ![image](https://user-images.githubusercontent.com/7944350/211197590-bb093b06-31c0-436e-b40e-e9979703b648.png)

Hi, I'd like to ask you some questions about this. You just recommended re-running the data generation script:
```
conda activate icon
python -m scripts.render_batch -headless -out_dir data/
```
Now the data/thuman2 / SMPLX/XXXX. Obj and data/thuman2 / scans/XXXX. Obj are aligned perfectly . **But I wonder if I need to re-run the data generation script as following?**
`python -m scripts.visibility_batch -out_dir data/`
Because I tried to debug a model and found that the data/thuman2_36views/scans/xxxx/vis/ xxxx.obj changed. Although the difference did not significantly affect the visualization results of vedo, **I wonder if not re-running the second script will have any effect on the training?**

**Comment by YuliangXiu** [comment]
> > Hi @Zhangjzh and @Yuhuoo
> > I have corrected some bugs and updated the scripts for training data generation [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md).
> > Please re-download the `SMPL-X.zip`, and re-run the data generation scripts:
> > ```shell
> > conda activate icon
> > python -m scripts.render_batch -headless -out_dir data/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now `data/thuman2/smplx/xxxx.obj` and `data/thuman2/scans/xxxx.obj` are aligned perfectly
> > ![image](https://user-images.githubusercontent.com/7944350/211197590-bb093b06-31c0-436e-b40e-e9979703b648.png)
> 
> Hi, I'd like to ask you some questions about this. You just recommended re-running the data generation script:
> 
> ```
> conda activate icon
> python -m scripts.render_batch -headless -out_dir data/
> ```
> 
> Now the data/thuman2 / SMPLX/XXXX. Obj and data/thuman2 / scans/XXXX. Obj are aligned perfectly . **But I wonder if I need to re-run the data generation script as following?** `python -m scripts.visibility_batch -out_dir data/` Because I tried to debug a model and found that the data/thuman2_36views/scans/xxxx/vis/ xxxx.obj changed. Although the difference did not significantly affect the visualization results of vedo, **I wonder if not re-running the second script will have any effect on the training?**

Yes, you need to re-run the visibility computation since the visibility is computed on SMPL-X objs
