### ISSUE TITLE
Bug with kornia

### ISSUE THREAD

**Issue by lllllialois** [YuliangXiu/ICON#172]
It seem that there is something wrong with kornia ,my kornia version is 0.6.9
I meet this bug`:

```bash
Traceback (most recent call last):
  File "/home/lia/anaconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lia/anaconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lia/projects/ICON-master/apps/infer.py", line 33, in <module>
    from lib.dataset.TestDataset import TestDataset
  File "/home/lia/projects/ICON-master/lib/dataset/TestDataset.py", line 19, in <module>
    from lib.pixielib.pixie import PIXIE
  File "/home/lia/projects/ICON-master/lib/pixielib/pixie.py", line 31, in <module>
    from .utils import tensor_cropper
  File "/home/lia/projects/ICON-master/lib/pixielib/utils/tensor_cropper.py", line 10, in <module>
    from kornia.geometry.transform.imgwarp import (warp_perspective,
  File "/home/lia/anaconda3/envs/icon/lib/python3.8/site-packages/kornia/__init__.py", line 3, in <module>
    from . import filters
  File "/home/lia/anaconda3/envs/icon/lib/python3.8/site-packages/kornia/filters/__init__.py", line 2, in <module>
    from .blur_pool import BlurPool2D, MaxBlurPool2D, blur_pool2d, edge_aware_blur_pool2d, max_blur_pool2d
  File "/home/lia/anaconda3/envs/icon/lib/python3.8/site-packages/kornia/filters/blur_pool.py", line 7, in <module>
    from kornia.testing import KORNIA_CHECK, KORNIA_CHECK_SHAPE
  File "/home/lia/anaconda3/envs/icon/lib/python3.8/site-packages/kornia/testing/__init__.py", line 10, in <module>
    from torch.testing import assert_close as _assert_close
ImportError: cannot import name 'assert_close' from 'torch.testing' (/home/lia/anaconda3/envs/icon/lib/python3.8/site-packages/torch/testing/__init__.py)
```
well, after checking the file `/home/lia/anaconda3/envs/icon/lib/python3.8/site-packages/torch/testing/__init__.py `in ubuntu and colab, I found that these two files are different, the file in ubuntu doesn't have assert_close, which is different with the file in colab
ubuntu
![2023-02-01 16-59-45 的屏幕截图](https://user-images.githubusercontent.com/105269874/215997633-244db587-4e79-491e-96aa-689b808a81bc.png)
colab
![2023-02-01 16-56-55 的屏幕截图](https://user-images.githubusercontent.com/105269874/215997707-3d32d311-4094-469f-9885-db02ff8d6254.png)
the torch version is 1.8.2, the same as you mention.
![2023-02-01 17-01-47 的屏幕截图](https://user-images.githubusercontent.com/105269874/215998073-a4e0dcd7-9caf-4c79-aa14-cb6fb0438772.png)

it seems that the kornia version and the torch version don't match.

**Comment by lllllialois** [comment]
well ,after checking the file `/home/lia/anaconda3/envs/icon/lib/python3.8/site-packages/torch/testing/__init__.py `in ubuntu and colab ,I found that these two file is different, the file in ubuntu dosen't have assert_close,which is different with the file in colab
![2023-02-01 16-59-45 的屏幕截图](https://user-images.githubusercontent.com/105269874/215997633-244db587-4e79-491e-96aa-689b808a81bc.png)
![2023-02-01 16-56-55 的屏幕截图](https://user-images.githubusercontent.com/105269874/215997707-3d32d311-4094-469f-9885-db02ff8d6254.png)
the torch version is 1.8.2,the same as you mention.
![2023-02-01 17-01-47 的屏幕截图](https://user-images.githubusercontent.com/105269874/215998073-a4e0dcd7-9caf-4c79-aa14-cb6fb0438772.png)

**Comment by lllllialois** [comment]
ok it works after I uninstall kornia 0.6.9 and install kornia 0.6.8,kornia 0.6.9 only support torch>=1.9.1
