### ISSUE TITLE
Colab demo error 

### ISSUE THREAD

**Issue by sunjc0306** [YuliangXiu/ICON#20]
Hi!
I would like to finish the test in the colab demo. However, it has a problem.
Before I test this demo, all code is modified. 

Traceback (most recent call last):
  File "infer.py", line 308, in <module>
    verts_pr, faces_pr, _ = model.test_single(in_tensor)
  File "/content/ICON/apps/ICON.py", line 736, in test_single
    sdf = self.reconEngine(opt=self.cfg,
  File "/usr/local/envs/icon/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/ICON/apps/../lib/common/seg3d_lossless.py", line 148, in forward
    return self._forward_faster(**kwargs)
  File "/content/ICON/apps/../lib/common/seg3d_lossless.py", line 170, in _forward_faster
    occupancys = self.batch_eval(coords, **kwargs)
  File "/content/ICON/apps/../lib/common/seg3d_lossless.py", line 139, in batch_eval
    occupancys = self.query_func(**kwargs, points=coords2D)
  File "/content/ICON/apps/../lib/common/train_util.py", line 338, in query_func
    preds = netG.query(features=features,
  File "/content/ICON/apps/../lib/net/HGPIFuNet.py", line 285, in query
    smpl_sdf, smpl_norm, smpl_cmap, smpl_ind = cal_sdf_batch(
  File "/content/ICON/apps/../lib/dataset/mesh_util.py", line 255, in cal_sdf_batch
    residues, normals, pts_cmap, pts_ind = func(
  File "/usr/local/envs/icon/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/bvh_distance_queries/mesh_distance.py", line 105, in forward
    output = self.search_tree(triangles, points)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/bvh_distance_queries/bvh_search_tree.py", line 109, in forward
    output = BVHFunction.apply(
  File "/usr/local/envs/icon/lib/python3.8/site-packages/bvh_distance_queries/bvh_search_tree.py", line 42, in forward
    outputs = bvh_distance_queries_cuda.distance_queries(
RuntimeError: after reduction step 1: cudaErrorInvalidDevice: invalid device ordinal

**Comment by YuliangXiu** [comment]
I tried the colab and met the same issue, will let you know when I find the hidden bug.

**Comment by YuliangXiu** [comment]
@sunjc0306 I have replaced the `bvh-distance-queries` with `PyTorch3D+Kaolin`, thus you don't need to install it anymore.

**Comment by YuliangXiu** [comment]
@sunjc0306 I just updated the installation scripts, colab can work well for now.

<a href='https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing' style='padding-left: 0.5rem;'>
      <img src='https://colab.research.google.com/assets/colab-badge.svg' alt='Google Colab'>
    </a>
