### ISSUE TITLE
Error while running demo colab

### ISSUE THREAD

**Issue by ujjawalcse** [YuliangXiu/ICON#21]
Hey @YuliangXiu ,
I'm facing the below error after running the demo script,

```
%cd /content/ICON/apps
!source activate icon && python infer.py -cfg ../configs/icon-filter.yaml -loop_smpl 100 -loop_cloth 100 -colab -gpu 0
```

```
Traceback (most recent call last):
  File "infer.py", line 87, in <module>
    dataset = TestDataset(
  File "/content/ICON/apps/../lib/dataset/TestDataset.py", line 73, in __init__
    self.hps = pymaf_net(path_config.SMPL_MEAN_PARAMS,
  File "/content/ICON/apps/../lib/pymaf/models/pymaf_net.py", line 361, in pymaf_net
    model = PyMAF(smpl_mean_params, pretrained)
  File "/content/ICON/apps/../lib/pymaf/models/pymaf_net.py", line 207, in __init__
    Regressor(feat_dim=ref_infeat_dim,
  File "/content/ICON/apps/../lib/pymaf/models/pymaf_net.py", line 36, in __init__
    self.smpl = SMPL(SMPL_MODEL_DIR, batch_size=64, create_transl=False)
  File "/content/ICON/apps/../lib/pymaf/models/smpl.py", line 23, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/envs/icon/lib/python3.8/site-packages/smplx/body_models.py", line 149, in __init__
    data_struct = Struct(**pickle.load(smpl_file,
_pickle.UnpicklingError: invalid load key, '\x03'.
```

I tried the below code snippet and it's working fine  in colab cell,

```
import pickle
with open('/content/ICON/data/smpl_related/models/smpl/SMPL_FEMALE.pkl','rb') as f1:
  d1=pickle.load(f1,encoding='latin1')
print(d1) 
```

Can anyone please suggest to tackle this issue?

**Comment by YuliangXiu** [comment]
I guess this is related to the version of python, are u using python3?

**Comment by ujjawalcse** [comment]
Yaa, I'm using Python3. And as per ICON environment created ,it's python 3.8.
 When I'm running outside this environment, it's working fine.
But when trying with icon environment, it's throwing the error.
I don't know why.

**Comment by YuliangXiu** [comment]
I just updated the installation scripts, colab can work well for now.

<a href='https://colab.research.google.com/drive/1-AWeWhPvCTBX0KfMtgtMk10uPU05ihoA?usp=sharing' style='padding-left: 0.5rem;'>
      <img src='https://colab.research.google.com/assets/colab-badge.svg' alt='Google Colab'>
    </a>

**Comment by ujjawalcse** [comment]
Thanks.
