### ISSUE TITLE
A question of datasets

### ISSUE THREAD

**Issue by yangqinhui0423** [YuliangXiu/ICON#239]
Dear authors, thanks for your excellent work!
I have a question when I run bash **fetch_data.sh**.
I can only download part of the files.
For example,the structure of one folder on the website is as follows:
![image](https://github.com/YuliangXiu/ICON/assets/112925344/46c2c780-4bcc-4775-a709-0a782f442729)
But in my folder,it only includes these：
![image](https://github.com/YuliangXiu/ICON/assets/112925344/d44d8a51-0710-454b-abfe-2a3508a78a6e)

So when I run **python -m scripts.render_batch -debug -headless**, it report error as follows：
![image](https://github.com/YuliangXiu/ICON/assets/112925344/c4a1b970-2f64-4258-af70-ea21359a5c68)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ciciyang/code/ICON/lib/dataset/../../data/smpl_related/smpl_data/smplx_faces.npy'

**Comment by yangqinhui0423** [comment]
Then I change the **smpl_type** from "smplx" to "smpl":
![image](https://github.com/YuliangXiu/ICON/assets/112925344/e9d08ec3-0dd2-4edd-a817-af353ac7ab75)
After I run **python -m scripts.render_batch -debug -headless**, it report error as follows：
_![image](https://github.com/YuliangXiu/ICON/assets/112925344/08696a31-eecc-4458-ad3b-8526c04defe8)
Start Rendering thuman2 with 36 views, 512x512 size.
Output dir: ./debug/thuman2_36views
Rendering types: ['light', 'normal', 'depth']
  0%|                                                                                                                                                                    | 0/2 [00:03<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ciciyang/miniconda3/envs/icon/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ciciyang/code/ICON/scripts/render_batch.py", line 74, in render_subject
    rescale_fitted_body, joints = load_fit_body(
  File "/home/ciciyang/code/ICON/lib/renderer/mesh.py", line 61, in load_fit_body
    param[key] = torch.as_tensor(param[key])
TypeError: can't convert np.ndarray of type numpy.uint32. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ciciyang/miniconda3/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ciciyang/miniconda3/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ciciyang/code/ICON/scripts/render_batch.py", line 254, in <module>
    for _ in tqdm(
  File "/home/ciciyang/miniconda3/envs/icon/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/ciciyang/miniconda3/envs/icon/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: can't convert np.ndarray of type numpy.uint32. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool._

**Comment by yangqinhui0423** [comment]
Then I add "param[key] = param[key].astype(np.float32)" before  “param[key] = torch.as_tensor(param[key])” .
I go back to the same question
![image](https://github.com/YuliangXiu/ICON/assets/112925344/3859ea96-d850-4242-ba2c-8ffbe44330fe)
