### ISSUE TITLE
ModuleNotFoundError: No module named'kaolin'

### ISSUE THREAD

**Issue by cedro3** [YuliangXiu/ICON#41]
When I run the following command in Colab
% cd / content / ICON / apps
! source activate icon && python infer.py -cfg ../configs/icon-filter.yaml -loop_smpl 100 -loop_cloth 0 -colab -gpu 0 -export_video -in_dir ../examples

I get the following error
/ content / ICON / apps
Traceback (most recent call last):
   File "infer.py", line 29, in <module>
     from ICON import ICON
   File "/content/ICON/apps/ICON.py", line 36, in <module>
     from lib.dataset.mesh_util import SMPLX, update_mesh_shape_prior_losses, get_visibility
   File "/content/ICON/apps/../lib/dataset/mesh_util.py", line 28, in <module>
     from kaolin.ops.mesh import check_sign
ModuleNotFoundError: No module named'kaolin'

What should I do?

**Comment by cedro3** [comment]
I was able to solve it myself.

1) Change the directory where kaolin and neural_voxelization_layer are installed from / content / ICON to / content / ICON / apps.
2) Copy SMPL_NEUTRAL.pkl to data / smpl_related / models / smpl

After executing 1) and 2), it worked normally.
Thank you so much.
