### ISSUE TITLE
problem when use pixie as hps_type

### ISSUE THREAD

**Issue by pinga999** [YuliangXiu/ICON#43]
Sorry to open similar issue.

It's an issue that came up before, but it's not solved well, so I'm asking you again
#30  related to iss_30 

The problem has not been solved for about five days.

It was changed to 5.1.1 according to the advice of the issue, but the problem remained the same and restored to the latest version of PyYAML. Is there any other solution?

> Sorry, try to use PyYAML==5.1.1

```
Traceback (most recent call last):
  File "infer.py", line 96, in <module>
    dataset = TestDataset(dataset_param, device)
  File "/workspace/fashion-ICON/apps/../lib/dataset/TestDataset.py", line 105, in __init__
    self.hps = PIXIE(config = pixie_cfg, device=self.device)
  File "/workspace/fashion-ICON/apps/../lib/pixielib/pixie.py", line 49, in __init__
    self._create_model()
  File "/workspace/fashion-ICON/apps/../lib/pixielib/pixie.py", line 115, in _create_model
    self.smplx = SMPLX(self.cfg.model).to(self.device)
  File "/workspace/fashion-ICON/apps/../lib/pixielib/models/SMPLX.py", line 156, in __init__
    self.extra_joint_selector = JointsFromVerticesSelector(
  File "/workspace/fashion-ICON/apps/../lib/pixielib/models/lbs.py", line 399, in __init__
    data = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
```

by original repo's issue (https://github.com/YuliangXiu/ICON/issues/30)

refer to upper comments, this error might be resolved by install PyYAML==5.1.1 but
It makes error again
```
Traceback (most recent call last):
  File "infer.py", line 102, in <module>
    for data in pbar:
  File "/opt/conda/envs/icon/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/workspace/fashion-ICON/apps/../lib/dataset/TestDataset.py", line 191, in __getitem__
    preds_dict = self.hps.forward(img_hps.to(self.device))
  File "/workspace/fashion-ICON/apps/../lib/pixielib/pixie.py", line 56, in forward
    param_dict = self.encode({'body': {'image': data}}, threthold=True, keep_local=True, copy_and_paste=False)
  File "/opt/conda/envs/icon/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/fashion-ICON/apps/../lib/pixielib/pixie.py", line 259, in encode
    cropped_image, cropped_joints_dict = self.part_from_body(image_hd, part_name, points_dict)
  File "/workspace/fashion-ICON/apps/../lib/pixielib/pixie.py", line 166, in part_from_body
    cropped_image, tform = self.Cropper[cropper_key].crop(
  File "/workspace/fashion-ICON/apps/../lib/pixielib/utils/tensor_cropper.py", line 98, in crop
    cropped_image, tform = crop_tensor(image, center, bbox_size, self.crop_size)
  File "/workspace/fashion-ICON/apps/../lib/pixielib/utils/tensor_cropper.py", line 78, in crop_tensor
    cropped_image = warp_affine(
TypeError: warp_affine() got an unexpected keyword argument 'flags'
```
Are there any solution to run pixie module?

**Comment by YuliangXiu** [comment]
Kornia changed the API of warp_affine, you could change `flags` to `mode` or install `kornia==0.4.0`

**Comment by pinga999** [comment]
> Kornia changed the API of warp_affine, you could change `flags` to `mode` or install `kornia==0.4.0`

I changed `kornia==0.4.0` but error about pytorch 3d, So I want to try  change `flags` to `mode` but I don't understand what flags means and know where flags located. 

I understand very well that this comment does not correspond to the propensity of the issue. But I wanted to know, so I left a question with you.

Thanks.

**Comment by YuliangXiu** [comment]
Please check the code details and the Kornia document.

**Comment by pinga999** [comment]
> Please check the code details and the Kornia document.

Special Thanks, Issue resolved 

Should I close the issue?

Thanks
