### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by Andyen512** [YuliangXiu/ICON#69]
bash scripts/vis_batch.sh debug all

```bash
thuman2 START----------
Debug visibility
Visibility thuman2 0300
Traceback (most recent call last):
  File "scripts/vis_single.py", line 58, in <module>
    smpl_vis = get_visibility(xy, z, smpl_faces)
  File "/home/liaoqi/Code/ICON/lib/dataset/mesh_util.py", line 207, in get_visibility
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "/home/liaoqi/Code/ICON/pytorch3d/pytorch3d/renderer/mesh/rasterize_meshes.py", line 234, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
File "/home/liaoqi/Code/ICON/pytorch3d/pytorch3d/renderer/mesh/rasterize_meshes.py", line 308, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: CUDA error: invalid device function
scripts/vis_single.sh: line 32: 15195 Segmentation fault      (core dumped) python $PYTHON_SCRIPT -s $SUBJECT -o $SAVE_DIR -r $NUM_VIEWS -m $MODE
thuman2 END----------
```
cuda10.0  pytorch3d 0.6.2  pytorch 1.6.0

**Comment by Andyen512** [comment]
I've upgrade my cuda to 11.0 and it worked.
