### ISSUE TITLE
hope for suggestion about solving EGL error

### ISSUE THREAD

**Issue by liwenssss** [YuliangXiu/ICON#70]
Hi, I am very interested in your work and want to try.  But I got an EGL error when I run bash scripts/render_batch.sh debug all：

```
Rendering thuman2 0300
Traceback (most recent call last):
  File "scripts/render_single.py", line 45, in <module>
    initialize_GL_context(width=size, height=size, egl=egl)
  File "/home/lws/code/ICON-master/lib/renderer/gl/init_gl.py", line 23, in initialize_GL_context
    create_opengl_context((width, height))
  File "/home/lws/code/ICON-master/lib/renderer/gl/glcontext.py", line 115, in create_opengl_context
    egl_surf = egl.eglCreatePbufferSurface(egl_display, egl_cfg,
  File "/home/lws/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_BAD_CONFIG,
        baseOperation = eglCreatePbufferSurface,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7efe7087f640>,
                <OpenGL._opaque.EGLConfig_pointer object at 0x7efe7087fdc0>,
                <lib.renderer.gl.glcontext.c_int_Array_5 object at 0x7efe7087fe40>,
        ),
        result = <OpenGL._opaque.EGLSurface_pointer object at 0x7efe6e58a140>
)
thuman2 END----------

```

I try to solve it and google for the solutions. Have you met the problem before or can you give me any advice?

**Comment by Andyen512** [comment]
May be you are using headless rendering, I've also met this problem, but I solved it by refering this [Issue](https://github.com/shunsukesaito/PIFu/issues/49)

**Comment by liwenssss** [comment]
> May be you are using headless rendering, I've also met this problem, but I solved it by refering this [Issue](https://github.com/shunsukesaito/PIFu/issues/49)

Thx for your help. But it seems not solve my problem:
```
(icon) root@lwsVM:~/code/ICON-master# bash scripts/render_batch.sh debug all
thuman2 START----------
Debug renderer
Rendering thuman2 0300
Traceback (most recent call last):
  File "scripts/render_single.py", line 46, in <module>
    initialize_GL_context(width=size, height=size, egl=egl)
  File "/home/lws/code/ICON-master/lib/renderer/gl/init_gl.py", line 23, in initialize_GL_context
    create_opengl_context((width, height))
  File "/home/lws/code/ICON-master/lib/renderer/gl/glcontext.py", line 110, in create_opengl_context
    egl_display = create_initialized_headless_egl_display()
  File "/home/lws/code/ICON-master/lib/renderer/gl/glcontext.py", line 84, in create_initialized_headless_egl_display
    for device in egl_get_devices():
  File "/home/lws/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/EGL/EXT/device_base.py", line 34, in egl_get_devices
    if eglQueryDevicesEXT(max_count,devices,count):
  File "/home/lws/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function eglQueryDevicesEXT, check for bool(eglQueryDevicesEXT) before calling
thuman2 END----------
```
by the way, I install pyopengl 3.1.5

**Comment by YuliangXiu** [comment]
Have you installed EGL and set `egl=True` as [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md)?

**Comment by liwenssss** [comment]
> Have you installed EGL and set `egl=True` as [dataset.md](https://github.com/YuliangXiu/ICON/blob/master/docs/dataset.md)?

Yes, I follow every step in the .md file. And the error seems wired "EGL_BAD_CONFIG"..

**Comment by xiangli93** [comment]
> Hi, I am very interested in your work and want to try. But I got an EGL error when I run bash scripts/render_batch.sh debug all：
> 
> ```shell
> Rendering thuman2 0300
> Traceback (most recent call last):
>   File "scripts/render_single.py", line 45, in <module>
>     initialize_GL_context(width=size, height=size, egl=egl)
>   File "/home/lws/code/ICON-master/lib/renderer/gl/init_gl.py", line 23, in initialize_GL_context
>     create_opengl_context((width, height))
>   File "/home/lws/code/ICON-master/lib/renderer/gl/glcontext.py", line 115, in create_opengl_context
>     egl_surf = egl.eglCreatePbufferSurface(egl_display, egl_cfg,
>   File "/home/lws/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
>     return self( *args, **named )
>   File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
> OpenGL.raw.EGL._errors.EGLError: EGLError(
>         err = EGL_BAD_CONFIG,
>         baseOperation = eglCreatePbufferSurface,
>         cArguments = (
>                 <OpenGL._opaque.EGLDisplay_pointer object at 0x7efe7087f640>,
>                 <OpenGL._opaque.EGLConfig_pointer object at 0x7efe7087fdc0>,
>                 <lib.renderer.gl.glcontext.c_int_Array_5 object at 0x7efe7087fe40>,
>         ),
>         result = <OpenGL._opaque.EGLSurface_pointer object at 0x7efe6e58a140>
> )
> thuman2 END----------
> ```
> 
> I try to solve it and google for the solutions. Have you met the problem before or can you give me any advice?

Could you share the solutions?

**Comment by liwenssss** [comment]
> > Hi, I am very interested in your work and want to try. But I got an EGL error when I run bash scripts/render_batch.sh debug all：
> > ```shell
> > Rendering thuman2 0300
> > Traceback (most recent call last):
> >   File "scripts/render_single.py", line 45, in <module>
> >     initialize_GL_context(width=size, height=size, egl=egl)
> >   File "/home/lws/code/ICON-master/lib/renderer/gl/init_gl.py", line 23, in initialize_GL_context
> >     create_opengl_context((width, height))
> >   File "/home/lws/code/ICON-master/lib/renderer/gl/glcontext.py", line 115, in create_opengl_context
> >     egl_surf = egl.eglCreatePbufferSurface(egl_display, egl_cfg,
> >   File "/home/lws/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
> >     return self( *args, **named )
> >   File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
> > OpenGL.raw.EGL._errors.EGLError: EGLError(
> >         err = EGL_BAD_CONFIG,
> >         baseOperation = eglCreatePbufferSurface,
> >         cArguments = (
> >                 <OpenGL._opaque.EGLDisplay_pointer object at 0x7efe7087f640>,
> >                 <OpenGL._opaque.EGLConfig_pointer object at 0x7efe7087fdc0>,
> >                 <lib.renderer.gl.glcontext.c_int_Array_5 object at 0x7efe7087fe40>,
> >         ),
> >         result = <OpenGL._opaque.EGLSurface_pointer object at 0x7efe6e58a140>
> > )
> > thuman2 END----------
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I try to solve it and google for the solutions. Have you met the problem before or can you give me any advice?
> 
> Could you share the solutions?

sorry, I have something import interrupting the current progress. If I solve the problem, I will tell you.
