### ISSUE TITLE
IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by Yuhuoo** [YuliangXiu/ICON#75]
I have got and error When I used the command of "bash scripts/render_batch.sh gen all" to generate training data. But it was so strange that the program was still working. I don't know the error if this mistake will  affect the results. The complete log as follows.

```bash
(ICON) root@Ibdc3c0268004012f8:/hy-tmp/ICON# bash scripts/render_batch.sh gen all
thuman2 START----------
processing all the subjects
/hy-tmp/ICON/scripts/../lib/renderer/mesh.py:374: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  uvs = np.array(uv_data)
Traceback (most recent call last):
  File "/hy-tmp/ICON/scripts/render_single.py", line 67, in <module>
    vertices, faces, normals, faces_normals, textures, face_textures = load_scan(mesh_file, with_normal=True, with_texture=True)
  File "/hy-tmp/ICON/scripts/../lib/renderer/mesh.py", line 378, in load_scan
    norms = compute_normal(vertices, faces)
  File "/hy-tmp/ICON/scripts/../lib/renderer/mesh.py", line 414, in compute_normal
    tris = vertices[faces]
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by Yuhuoo** [comment]
The error occurred  just due to my dataset.
