### ISSUE TITLE
OpenGL.error.GLError: GLError(	err = 1282....)

### ISSUE THREAD

**Issue by BTWBB** [YuliangXiu/ICON#80]
Traceback (most recent call last):
  File "scripts/render_single.py", line 115, in <module>
    rndr = PRTRender(width=size, height=size, ms_rate=16, egl=egl)
  File "/data1/supersmpl/dy/ReCurrence/ICON/lib/renderer/gl/prt_render.py", line 35, in __init__
    CamRender.__init__(self,
  File "/data1/supersmpl/dy/ReCurrence/ICON/lib/renderer/gl/cam_render.py", line 32, in __init__
    Render.__init__(self,
  File "/data1/supersmpl/dy/ReCurrence/ICON/lib/renderer/gl/render.py", line 96, in __init__
    glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE,
  File "/data1/supersmpl/dy/.conda/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glTexImage2DMultisample,
	cArguments = (
		GL_TEXTURE_2D_MULTISAMPLE,
		16,
		GL_RGBA32F,
		512,
		512,
		GL_TRUE,
	)
)

Maybe it's because [glTexImage2DMultisample](http://mcfletch.github.io/pyopengl/documentation/manual/glTexImage2DMultisample.html) is available only if the GL version is 3.2 or greater.  However I can't install pyopengl 3.2  which can't be found!

**Comment by YuliangXiu** [comment]
same issue #60
