### ISSUE TITLE
cannot run on colab

### ISSUE THREAD

**Issue by Holmes-Alan** [YuliangXiu/ICON#89]
I followed the steps to download and install all the files and they all worked out. However, when I tried to test it on images as

!source activate icon && python -m apps.infer -cfg ./configs/icon-filter.yaml -loop_smpl 100 -loop_cloth 0 -colab -gpu 0 -export_video -in_dir ./examples

I got errors as follows:

```bash

Traceback (most recent call last):
  File "/usr/local/envs/icon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/icon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/ICON/apps/infer.py", line 372, in <module>
    verts_pr, faces_pr, _ = model.test_single(in_tensor)
  File "/content/ICON/apps/ICON.py", line 754, in test_single
    verts_pr, faces_pr = self.reconEngine.export_mesh(sdf)
  File "/content/ICON/lib/common/seg3d_lossless.py", line 585, in export_mesh
    final = occupancys[:-1, :-1, :-1].contiguous()
TypeError: 'NoneType' object is not subscriptable
```

**Comment by YuliangXiu** [comment]
same issue #65
