### ISSUE TITLE
numpy version issue

### ISSUE THREAD

**Issue by KaifCHANG** [YuliangXiu/ICON#98]
I follow the [Installation Instruction](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md) to build the environment.
When I run the bash scripts/render_batch.sh debug all an error occurred.

> (icon) avlab@avlab-X570-GAMING-X:/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON$ bash scripts/render_batch.sh debug all
thuman2 START----------
Debug renderer
Rendering thuman2 0001
/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "render_single.py", line 1, in <module>
    import lib.renderer.opengl_util as opengl_util
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/renderer/opengl_util.py", line 18, in <module>
    from lib.renderer.mesh import load_scan, compute_tangent, compute_normal, load_obj_mesh_mtl
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/renderer/mesh.py", line 18, in <module>
    from lib.dataset.mesh_util import SMPLX
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/dataset/mesh_util.py", line 32, in <module>
    from lib.pymaf.utils.imutils import uncrop
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/pymaf/utils/imutils.py", line 11, in <module>
    from rembg.bg import remove
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/rembg/__init__.py", line 5, in <module>
    from .bg import remove
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/rembg/bg.py", line 9, in <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/pymatting/__init__.py", line 2, in <module>
    from pymatting.util import *
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/pymatting/util/__init__.py", line 2, in <module>
    from pymatting.util.kdtree import KDTree, knn
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/pymatting/util/kdtree.py", line 2, in <module>
    from numba import njit, prange
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/numba/__init__.py", line 206, in <module>
    _ensure_critical_deps()
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/numba/__init__.py", line 146, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.22 or less")
ImportError: Numba needs NumPy 1.22 or less
thuman2 END----------

After type in pip install numpy==1.22.4 another error occurred.

> Successfully installed numpy-1.22.4
(icon) avlab@avlab-X570-GAMING-X:/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON$ bash scripts/render_batch.sh debug all
thuman2 START----------
Debug renderer
Rendering thuman2 0001
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "render_single.py", line 97, in <module>
    rndr_depth = ColorRender(width=size, height=size, egl=egl)
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/renderer/gl/color_render.py", line 34, in __init__
    CamRender.__init__(self,
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/renderer/gl/cam_render.py", line 32, in __init__
    Render.__init__(self,
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/renderer/gl/render.py", line 54, in __init__
    shader_list.append(loadShader(GL_VERTEX_SHADER, program_file))
  File "/media/avlab/0623aea6-2bc6-43c9-8861-6ef2a5388576/3d_human/ICON/lib/renderer/gl/framework.py", line 34, in loadShader
    status = glGetShaderiv(shader, GL_COMPILE_STATUS)
  File "src/latebind.pyx", line 51, in OpenGL_accelerate.latebind.Curry.__call__
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 268, in glGetShaderiv
    status = arrays.GLintArray.zeros( (1,))
  File "src/arraydatatype.pyx", line 219, in OpenGL_accelerate.arraydatatype.ArrayDatatype.zeros
  File "src/arraydatatype.pyx", line 224, in OpenGL_accelerate.arraydatatype.ArrayDatatype.c_zeros
  File "src/arraydatatype.pyx", line 69, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_get_output_handler
  File "src/arraydatatype.pyx", line 80, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_handler_by_plugin_name
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/plugins.py", line 18, in load
    return importByName( self.import_path )
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/plugins.py", line 45, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/home/avlab/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/arrays/numpymodule.py", line 28, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
SystemError: execution of module OpenGL_accelerate.numpy_formathandler raised unreported exception
thuman2 END----------**

I try to solve it and google for the solutions. Have you met the problem before or can you give me any advice?

**Comment by YuliangXiu** [comment]
I haven't met such error, but here is my version info:

```bash
>>> OpenGL.__version__
'3.1.1a1'
>>> numpy.__version__
'1.21.5'
>>> rembg.__version__
'2.0.13'
```

**Comment by yangqinhui0423** [comment]
I met same error. Have you solved it? If you have solved it, could you give me some advice? Thanks very much!

**Comment by chuanfushen** [comment]
I have met this issue, and I have fixed it by updating numpy:

```
pip install -U numpy
```
